export const Actiontypes={
    SET_POLICIES : "SET_POLICIES",
    SELECTED_POLICY: "SELECTED_POLICY",
    SET_POLICYPURCHASES: "SET_POLICYPURCHASES",
    SELECTED_POLICYPURCHASE: "SELECTED_POLICYPURCHASE",
   }